/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExportSetting;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test public void test001() throws Exception {
//        Main.main(null);
    }
}
